package pl.fernikq.core.inventory.enums.guild;

public enum GuildPanelActionType {

    OPEN_PANEL_MENU,

    OPEN_MEMBER_CHOOSE,
    OPEN_RESOURCES,
    OPEN_TREASURE,
    EXECUTE_TIME_RENEW,
    EXECUTE_CUBOID_ENLARGE,
    EXECUTE_MEMBERS_ENLARGE,
    EXECUTE_ALLIANCES_ENLARGE,
    EXECUTE_TREASURE_ENLARGE,

    OPEN_MEMBER_PERMISSIONS,
    OPEN_MEMBER_PERMISSION_NEXT_PAGE,
    OPEN_MEMBER_PERMISSION_PREVIOUS_PAGE,

    CHANGE_PERMISSION,

    GIVE_COINS_TO_RESOURCES;
}
